version: "3.9"
services:
  ton-node:
    image: ton-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
        TELEMETRY: ${TELEMETRY}
        IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
        DUMP: ${DUMP}
    restart: always
    init: true
    tty: true
    volumes:
      - ton-db:/var/ton-work/db
    network_mode: host
    environment:
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
volumes:
  ton-db: