version: "3.9"
services:
  node:
    image: ton-node:latest
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
    restart: always
    init: true
    tty: true
    volumes:
      - ton-db:/var/ton-work/db
    network_mode: host
    environment:
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
volumes:
  ton-db: