version: "3.9"
services:
  node:
    image: ton-node:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    init: true
    tty: true
    volumes:
      - ton-db:/var/ton-work/db
    network_mode: host
    secrets:
      - config.json
volumes:
  ton-db:
secrets:
  config.json:
    file: private/config.json